export const metricConst = {
    'V': 'Voltage',
    'v': 'Voltage',
    '--': 'Power Factor',
    'A': 'Current',
    'kW': 'Power',
    'kVA': 'Apparent Power',
    'kVAr': 'Reactive Power',
    'kWh': 'Consumpution Reading',
    'hz': 'Frequency',
    'h': 'Running Time',
    '°C': 'Temperature',
    'mm/s': 'Velocity',
    'm/s': 'Acceleration',
    'm/s2': 'Acceleration',
    '(m/s2)': 'Acceleration',
    'Pa': 'Pressure',
    'KOH/g': 'Acid Index',
    'mgKOH/g': 'Acid Index',
    'rpm': 'Speed',
    'Kg': 'Weight',
    'hPa': 'Atmospheric Pressure',
    'Nm3/hr': 'Flow Rate',
    'ppm': 'Level'
}