export const groupByConfig = {
    "offilineDAC": [{ id: '', label: 'None' }, { id: 'CATEGORY', label: 'Categories'}, { id: 'TYPE', label: 'Type'}, { id: 'FREQUENCY', label: 'Frequency'}, { id: 'UPDATED BY', label: 'Updated by'}],
    "offilineDACDetail": [{ id: '', label: 'None' }, { id: 'METRICS', label: 'Metrics'}],
    "offilineProductionDAC": [{ id: '', label: 'None' }, { id: 'Asset', label: 'Asset'}, { id: 'Product', label: 'Product'}, { id: 'Unit', label: 'Unit'}, { id: 'FREQUENCY', label: 'Frequency'}, { id: 'Last Updated by', label: 'Updated by'}, { id: 'Last Updated on', label: 'Updated On'}],
    "offilineProductionDACDetail": [{ id: '', label: 'None' }, { id: 'Unit', label: 'Unit'}, { id: 'Last Updated by', label: 'Updated by'}, { id: 'Last Updated on', label: 'Updated On'}],
    "products": [{ id: '', label: 'None' }, { id: 'created_by', label: 'Added By' }, { id: 'updated_by', label: 'Updated By' }],
    "Workorder": [{ id: '', label: 'None' }, { id: 'product', label: 'Product' }],
    "Execution": [{ id: '', label: 'None' }, { id: 'entity', label: 'Asset' }, { id: ` order_id`, label: 'Work Order' }],
    "downtime_reason": [{ id: '', label: 'None' }, { id: 'type', label: 'Type' }, { id: 'Added by', label: 'Added By' }],
    "quality_reason": [{ id: '', label: 'None' }, { id: 'type', label: 'Type' }, { id: 'Added by', label: 'Added By' }],
    "performance_reason": [{ id: '', label: 'None' }, { id: 'Added by', label: 'Added By' }],
    "other_reason": [{ id: '', label: 'None' }, { id: 'Added by', label: 'Added By' }],
    "steel": [{ id: '', label: 'None' }, { id: 'added_bY', label: 'Added By' }, { id: 'Asset', label: 'Asset' }, { id: 'Product', label: 'Product' }, { id: 'added_on', label: 'Added On' }],
    "alarm_rule": [{ id: '', label: 'None' }, { id: 'Aggergation', label: 'Aggregation' }, { id: 'CriticalCheck', label: 'Critical Check' }, { id: 'EntityName', label: 'Entity Name' }, { id: 'Parameter', label: 'Parameter' }, { id: 'Recurringalarm', label: 'Recurring Alarm' }, { id: 'User', label: 'User' }, { id: 'WarningCheck', label: 'Warning Check' }, { id: 'alertType', label: 'Alert type' }],
    "production_work_order_report": [{ id: '', label: 'None' }, { id: 'shift', label: 'Shift' }, { id: 'operator', label: 'Operator'}],
    "steel_production_report": [{id: '', label: 'None'}],
    "downtime_report": [{ id: '', label: 'None'}, { id: 'Date', label: 'Date'}, { id: 'Reason_Type', label: 'Reason Type'}, { id: 'Reason', label: 'Reason'}, { id: 'Reason Tags', label: 'Reason Tags'}],
    "maintainance_error_logs_report": [{id: '', label: 'None'}],
    "quality_report": [{id: '', label: 'None'}, {id: 'marked_at', label: "Date"}],
    "sda_report": [{id: '', label: 'None'}, {id: 'severity', label: "Severity"}, {id: 'side', label: "Side"}, {id: 'defect_type', label: "Defect Type"}],
    "asset_health_tasks": [{id: '', label: 'None'}],
    "asset_health_alarms": [{id: '', label: 'None'}],
    "continuous_analytics": [{id: '', label: 'None'}],
    "superimpose_analytics": [{id: '', label: 'None'}],
    "channels_settings": [{id: '', label: 'None'}, {id: 'type', label: 'Type'}],
    "assets_settings": [{id: '', label: 'None'}, {id: 'Last Updated By', label: 'Updated By'}],
    "entity_settings": [{id: '', label: 'None'}, {id: 'Type', label: 'Type'}, {id: 'Last Updated By', label: 'Updated By'}],
    "toollife_settings": [{id: '', label: 'None'}, {id: 'Asset Type', label: 'Asset Type'}, {id: 'Last Updated by', label: 'Updated by'}],
    "instrument_settings": [{id: '', label: 'None'}, {id: 'addedby', label: 'Added By'}, {id: 'category', label: 'Category'}, {id: 'type', label: 'Type'}],
    "virtual_instrument_settings": [{id: '', label: 'None'}, {id: 'Last Updated By', label: 'Updated By'}],
    "gateway_settings": [{id: '', label: 'None'}, {id: 'AddedBy', label: 'Added By'}, {id: 'Location', label: 'Location'}],
    "matric_group":[{id: '', label: 'None'}],
    "metric_settings": [{id: '', label: 'None'}, {id: 'instrumentCategory', label: 'Instrument Category'}, {id: 'instrumentType', label: 'Instrument Type'}, {id: 'metricDatatype', label: 'Data Type'}, {id: 'metricType', label: 'Metric Type'}, {id: 'metricUnit', label: 'Metric Unit'}],
    "connectivity_table": [{id: '', label: 'None'}],
    "alert_table": [{id: '', label: 'None'}],
    "policy": [{id: '', label: 'None'}],
    "manage_instruments": [{id: '', label: 'None'}],
    "alerts_table":  [{id: '', label: 'None'},{id: 'Alarm Status', label: 'Criticality'}, {id: 'Metrics', label: 'Metrics'}, {id: 'Instrument', label: 'Instrument'},  {id: 'Acknowledge', label: 'Acknowledge'}, ],
    "faults_table": [{id: '', label: 'None'},{id: 'Criticality', label: 'Criticality'}, {id: 'Metrics', label: 'Metrics'}, {id: 'Instrument', label: 'Instrument'} ],
    "speed_feed":[{id: '', label: 'None'}, {id: 'Date', label: 'Date'}, { id: 'Shift', label: 'Shift'}, { id: 'spindle_status', label: 'Spindle Status'}, {id: 'feed_status', label: 'Feed Status'}],
    "neonix_enquiry": [{id: '', label: 'None'}, {id: 'Customer', label: 'Customer'}, {id: 'Enquiry Type', label: 'Enquiry Type'}, {id: 'Status', label: 'Status'}],
    "neonix_asset": [{id: '', label: 'None'}, {id: 'Asset Category', label: 'Asset Category'}, {id: 'Asset Type', label: 'Asset Type'}, {id: 'Asset Name', label: 'Asset Name'}],
    "neonix_operation": [{id: '', label: 'None'}],
    "route_card": [{id: '', label: 'None'}, {id: 'Asset', label: 'Asset'}, {id: 'Operator', label: 'Operator'}, {id: 'Product', label: 'Product'}, {id: 'Shift', label: 'Shift'}]
}