name: Stage Neo Web App

on:
  schedule:
    - cron: '35 * * * *'  # Runs every hour at the 35th minute
  workflow_dispatch:

jobs:
  check_commits:
    runs-on: ubuntu-latest
    outputs:
      has_commits: ${{ steps.check.outputs.has_commits }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: staging

      - name: Configure Git
        run: git fetch --unshallow

      - name: Check for commits in the last hour
        id: check
        run: |
          LAST_HOUR=$(date --utc --date='1 hour ago' +'%Y-%m-%dT%H:%M:%SZ')
          COMMITS=$(git log --since="$LAST_HOUR" --pretty=format:'%h' | wc -l)
          if [[ "$COMMITS" -gt 0 ]]; then
            echo "Commits found in the last hour: $COMMITS"
            echo "has_commits=true" >> "$GITHUB_OUTPUT"
          else
            echo "No commits in the last hour."
            echo "has_commits=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

  build_and_deploy_job:
    needs: check_commits
    if: "needs.check_commits.outputs.has_commits == 'true'"
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          ref: staging

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BAY_00D944000 }}
          app_build_command: 'yarn build:staging'
          action: "upload"
          app_location: "/" 
          output_location: "build"
          production_branch: "staging"
